### ISSUE TITLE
The second half of the work is run twice...

### ISSUE THREAD

**Issue by ghost** [aktech/gil_talk#1]
I think the intention here is to run different halves of the work.

https://github.com/aktech/gil_talk/blob/edc0320a6470a74e321e443e1d89beb65fe5bd0c/cpp_multithreading/c_threads.cpp#L27

pass `start` and `exclusive_end` (as is done in C-like `for` loops) to the threads, maybe?

**Comment by aktech** [comment]
Hi @mar77i the `arg` is passed as an argument to both the threads [here](https://github.com/aktech/gil_talk/blob/edc0320a6470a74e321e443e1d89beb65fe5bd0c/cpp_multithreading/c_threads.cpp#L30). Which is half of `N`. Where is the second half of work is run twice, I didn't understood that, can you elaborate?

**Comment by ghost** [comment]
Well I think the intention of the code is to have one thread count from `0` to `N/2` and the other from `N/2` to `N`...? - Otherwise, as in the current code, both threads end up counting through the same numbers?

**Comment by aktech** [comment]
@mar77i Yes both the threads count from 0 to N/2, because counting from 0 to N/2 is same as counting from N/2 to N. Does it makes any difference in your opinion?

**Comment by ghost** [comment]
I think this makes the whole effort a really detached, impractical example, but okay.

**Comment by aktech** [comment]
> I think this makes the whole effort a really detached, impractical example

Can you clarify, why this is an impractical example?
